import { test } from 'node:test';
import assert from 'node:assert/strict';
import express from 'express';
import { createServer } from 'node:http';
import mysql from 'mysql2/promise';
import dotenv from 'dotenv';
import { readFileSync } from 'node:fs';

test('HTTP e MySQL: isolamento A/B, identidade e transação financeira', { skip: process.env.SECURITY_INTEGRATION !== '1' }, async () => {
  dotenv.config({ path: '../.env' });
  process.env.DB_HOST = '127.0.0.1';
  process.env.DB_PORT = '3307';
  const { default: routes } = await import('../src/routes.js');
  const { default: verifyJWT } = await import('../src/middlewares/jwt.js');
  const { createSecurityGate } = await import('../src/middlewares/security.js');
  const { default: securityRepository } = await import('../src/repository/securityRepository.js');
  const { hashPassword } = await import('../src/helpers/password.js');
  const { migratePasswords } = await import('../src/scripts/migratePasswords.js');
  const { default: applicationDatabase } = await import('../src/repository/connection.js');
  const db = await mysql.createConnection({ host: process.env.DB_HOST, port: 3307, user: process.env.DB_USER, password: process.env.DB_PASSWORD, database: process.env.DB_NAME });
  const [[reportColumn]] = await db.query("SELECT IS_NULLABLE FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = ? AND TABLE_NAME = 'bug_reports' AND COLUMN_NAME = 'id_user'", [process.env.DB_NAME]);
  assert.equal(reportColumn?.IS_NULLABLE, 'YES', 'Banco de teste deve conter a migration 001.');
  const app = express(); app.use(express.json());
  app.use((req, res, next) => (req.path === '/login' && req.method === 'POST') ? next() : verifyJWT(req, res, next));
  app.use(createSecurityGate(securityRepository)); app.use(routes);
  const server = createServer(app);
  await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
  const base = `http://127.0.0.1:${server.address().port}`;
  const churchIds = []; const userIds = []; const departmentIds = []; const memberIds = [];
  const call = async (method, path, token, body) => {
    const response = await fetch(base + path, { method, headers: { 'content-type': 'application/json', ...(token ? { authorization: `Bearer ${token}` } : {}) }, ...(body ? { body: JSON.stringify(body) } : {}) });
    const text = await response.text();
    let parsed;
    try { parsed = text ? JSON.parse(text) : null; } catch { parsed = text; }
    return { status: response.status, body: parsed, setCookie: response.headers.get('set-cookie') };
  };
  try {
    const [withoutBalance] = await db.query('INSERT INTO igreja (nome,cnpj,cep,endereco,bairro,cidade,ministerio) VALUES (?,?,?,?,?,?,?)', ['Balance migration test', `b-${Date.now()}`, '00000000', 'Rua teste', 'Bairro', 'Cidade', 'Teste']);
    churchIds.push(withoutBalance.insertId);
    const migration = readFileSync(new URL('../src/repository/migrations/002_backfill_missing_balances.sql', import.meta.url), 'utf8');
    const start = migration.indexOf('INSERT INTO');
    const backfill = migration.slice(start, migration.indexOf(';', start) + 1);
    await db.query(backfill);
    await db.query(backfill);
    const [[backfilled]] = await db.query('SELECT COUNT(*) AS total FROM saldo WHERE id_igreja = ?', [withoutBalance.insertId]);
    assert.equal(backfilled.total, 1);
    for (const suffix of ['A', 'B']) {
      const [result] = await db.query('INSERT INTO igreja (nome,cnpj,cep,endereco,bairro,cidade,ministerio) VALUES (?,?,?,?,?,?,?)', [`Security Test ${suffix}`, `test-${Date.now()}-${suffix}`, '00000000', 'Rua teste', 'Bairro', 'Cidade', 'Teste']);
      churchIds.push(result.insertId);
      await db.query('INSERT INTO saldo (saldo_atual,data_atualizacao,id_igreja) VALUES (0,CURDATE(),?)', [result.insertId]);
      const email = `security-${Date.now()}-${suffix}@example.invalid`;
      const [created] = await db.query('INSERT INTO user(cod_membro,nome,email,senha,birth,cargo,id_igreja) VALUES (?,?,?,?,?,?,?)', [`test-${suffix}`, `Pastor ${suffix}`, email, await hashPassword('senha-de-teste-123'), '2000-01-01', 'Pastor', result.insertId]);
      userIds.push({ id: created.insertId, email });
      const [department] = await db.query('INSERT INTO departamentos(nome,birth,id_igreja) VALUES (?,?,?)', [`Departamento ${suffix}`, '2000-01-01', result.insertId]);
      departmentIds.push(department.insertId);
      const [member] = await db.query('INSERT INTO membro(cod_membro,nome,birth,novo_convertido,id_departamento,id_igreja) VALUES (?,?,?,?,?,?)', [`member-${suffix}`, `Membro ${suffix}`, '2000-01-01', 'Sim', department.insertId, result.insertId]);
      memberIds.push(member.insertId);
    }
    const [a,b] = churchIds.slice(-2);
    const [legacy] = await db.query('INSERT INTO user(cod_membro,nome,email,senha,birth,cargo,id_igreja) VALUES (?,?,?,?,?,?,?)', ['legacy', 'Legado', `legacy-${Date.now()}@example.invalid`, 'senha-legada', '2000-01-01', 'Obreiro', a]);
    assert.ok((await migratePasswords(applicationDatabase)) >= 1);
    const [[migrated]] = await db.query('SELECT senha FROM user WHERE id_user = ?', [legacy.insertId]);
    assert.match(migrated.senha, /^\$scrypt\$/);
    const loginA = await call('POST', '/login', null, { email: userIds[0].email, senha: 'senha-de-teste-123' });
    const loginB = await call('POST', '/login', null, { email: userIds[1].email, senha: 'senha-de-teste-123' });
    assert.equal(loginA.status, 200); assert.equal(loginB.status, 200);
    assert.match(loginA.setCookie || '', /od_session=.*HttpOnly.*SameSite=Lax/i);
    const tokenA = loginA.body.token, tokenB = loginB.body.token;
    const cookieA = loginA.setCookie.split(';')[0];
    assert.equal((await fetch(base + `/financas/${a}`, { headers: { Cookie: cookieA } })).status, 200);
    const logout = await fetch(base + '/login/logout', { method: 'POST', headers: { Cookie: cookieA, Origin: 'http://localhost:3000' } });
    assert.equal(logout.status, 200);
    assert.match(logout.headers.get('set-cookie') || '', /od_session=.*Expires=/i);
    assert.equal((await call('GET', `/financas/${a}`)).status, 401);
    assert.equal((await call('GET', `/financas/${a}`, tokenA)).status, 200);
    assert.equal((await call('GET', `/financas/${b}`, tokenA)).status, 403);
    assert.equal((await call('GET', `/financas/${b}`, tokenB)).status, 200);
    assert.equal((await call('GET', `/financas/${a}`, tokenB)).status, 403);
    const ownUser = await call('GET', '/cadastro', tokenA);
    assert.equal(ownUser.status, 201); assert.equal(ownUser.body.id_user, userIds[0].id); assert(!('senha' in ownUser.body));
    const ownUsers = await call('GET', '/cadastro/cadastro', tokenA);
    assert.equal(ownUsers.status, 200);
    assert(ownUsers.body.every(row => row.id_igreja === a && !('senha' in row)));
    const create = await call('POST', '/financas', tokenA, { tipo: 'Entrada', categoria: 'Oferta Simples', valor: '10.25', descricao: 'teste', data: '2026-10-05', id_igreja: a });
    assert.equal(create.status, 201, String(create.body));
    const invalidAmount = await call('POST', '/financas', tokenA, { tipo: 'Entrada', categoria: 'Oferta Simples', valor: '-1.00', descricao: 'teste', data: '2026-10-05', id_igreja: a });
    assert.equal(invalidAmount.status, 500);
    assert.equal(invalidAmount.body, 'Erro interno.');
    assert.equal((await call('POST', '/financas', tokenA, { tipo: 'Entrada', categoria: 'Oferta Simples', valor: '99.00', descricao: 'teste', data: '2026-10-05', id_igreja: b })).status, 403);
    assert.equal((await call('PUT', `/financas/${create.body.financasId}/${b}`, tokenB, { tipo: 'Saída', categoria: 'Oferta Simples', valor: '1.00', descricao: 'teste', data: '2026-10-05' })).status, 403);
    assert.equal((await call('PUT', `/financas/${create.body.financasId}/${a}`, tokenA, { tipo: 'Entrada', categoria: 'Oferta Simples', valor: '12.25', descricao: 'teste', data: '2026-10-05' })).status, 200);
    const balanceA = await call('GET', `/financas/saldo/${a}`, tokenA);
    const balanceB = await call('GET', `/financas/saldo/${b}`, tokenB);
    assert.equal(Number(balanceA.body.saldo), 12.25); assert.equal(Number(balanceB.body.saldo), 0);
    const pedido = await call('POST', '/pedido', tokenA, { nome_produto: 'Material', categoria_produto: 'Teste', quantidade: 1, data_pedido: '2026-10-05' });
    assert.equal(pedido.status, 201);
    const [[createdPedido]] = await db.query('SELECT id_pedido FROM pedidos WHERE id_igreja = ? ORDER BY id_pedido DESC LIMIT 1', [a]);
    assert.equal((await call('PUT', `/pedido/${createdPedido.id_pedido}/responder`, tokenB, { status_pedido: 'Entregue', data_entrega: '2026-10-06' })).status, 403);
    assert.equal((await call('PUT', `/pedido/${createdPedido.id_pedido}/responder`, tokenA, { status_pedido: 'Entregue', data_entrega: '2026-10-06' })).status, 200);
    assert.equal((await call('PUT', `/pedido/${createdPedido.id_pedido}/responder`, tokenA, { status_pedido: 'Recusado', motivo_recusa: 'repetido' })).status, 400);
    assert.equal((await call('DELETE', `/cadastro/${userIds[1].id}`, tokenA)).status, 403);
    assert.equal((await call('GET', `/membro/${memberIds[0]}`, tokenA)).status, 201);
    assert.equal((await call('GET', `/membro/${memberIds[1]}`, tokenA)).status, 403);
    assert.equal((await call('GET', `/membro/${memberIds[1]}`, tokenB)).status, 201);
    assert.equal((await call('DELETE', `/membro/${memberIds[1]}`, tokenA)).status, 403);
    assert.equal((await call('PUT', `/departamento/${departmentIds[1]}/${b}`, tokenA, { nome: 'Invadido', birth: '2000-01-01' })).status, 403);
    assert.equal((await call('PUT', `/departamento/${departmentIds[0]}/${a}`, tokenA, { nome: 'Atualizado', birth: '2000-01-01', data_congresso: null })).status, 200);
    const [[ownDepartment]] = await db.query('SELECT nome FROM departamentos WHERE id_departamento = ?', [departmentIds[0]]);
    assert.equal(ownDepartment.nome, 'Atualizado');
    const visitors = await call('GET', '/visitante/membros', tokenA);
    assert.equal(visitors.status, 201);
    assert(visitors.body.every(row => row.id_igreja === a));
    const usersB = await call('GET', `/cadastro/obreiros/${b}`, tokenA);
    assert.equal(usersB.status, 403);
    await db.query('UPDATE user SET senha = ? WHERE id_user = ?', [await hashPassword('senha-nova-para-teste'), userIds[0].id]);
    assert.equal((await call('GET', `/financas/${a}`, tokenA)).status, 401);
    const [report] = await db.query('INSERT INTO bug_reports(id_user,motivo,descricao,data_criacao) VALUES (?,?,?,NOW())', [userIds[1].id, 'teste', 'teste']);
    assert.equal((await call('DELETE', `/cadastro/${userIds[1].id}`, tokenB)).status, 200);
    const [[removed]] = await db.query('SELECT COUNT(*) AS total FROM user WHERE id_user = ?', [userIds[1].id]);
    assert.equal(removed.total, 0);
    const [[retained]] = await db.query('SELECT id_user FROM bug_reports WHERE id_report = ?', [report.insertId]);
    assert.equal(retained.id_user, null);
    await db.query('DELETE FROM bug_reports WHERE id_report = ?', [report.insertId]);
  } finally {
    for (const churchId of churchIds) {
      await db.query('DELETE FROM membro WHERE id_igreja = ?', [churchId]);
      await db.query('DELETE FROM departamentos WHERE id_igreja = ?', [churchId]);
      await db.query('DELETE FROM financas WHERE id_igreja = ?', [churchId]);
      await db.query('DELETE FROM pedidos WHERE id_igreja = ?', [churchId]);
      await db.query('DELETE FROM saldo WHERE id_igreja = ?', [churchId]);
      await db.query('DELETE FROM bug_reports WHERE id_user IN (SELECT id_user FROM user WHERE id_igreja = ?)', [churchId]);
      await db.query('DELETE FROM user WHERE id_igreja = ?', [churchId]);
      await db.query('DELETE FROM igreja WHERE id_igreja = ?', [churchId]);
    }
    await db.end(); await new Promise(resolve => server.close(resolve));
  }
});
